/* mem_layout.h - Auto-generated by gen_image.py. Do not edit. */
#ifndef CATZ_MEM_LAYOUT_H
#define CATZ_MEM_LAYOUT_H
#include <stdint.h>
#define CATZ_IMAGE_SIZE 75440u
#define CATZ_GUARD_BASE 9904u
#define CATZ_NUM_SEG 3
#define CATZ_ENTRY_SEG 2
#define CATZ_ENTRY_IP 0x003Cu
#define CATZ_STACK_SEG 0
#define CATZ_STACK_SP 0x0000u
#define CATZ_AUTO_DATA_SEG 3
static const uint32_t SEG_SEGMENT_BASE[4] = {
    9904,16,1728,8320,
};
#endif /* CATZ_MEM_LAYOUT_H */
