/* runtime_api.h - Auto-generated by gen_win16_stubs.py. Do not edit. */
/* Host runtime entry points referenced by the lifted CATZDLL code:  */
/* indirect-call dispatchers, software-interrupt handlers, and the   */
/* Win16 import shims (KERNEL/USER/GDI/SOSLIB03/WING/...).            */
#ifndef CATZ_RUNTIME_API_H
#define CATZ_RUNTIME_API_H

#include "cpu.h"

/* ---- Indirect call dispatchers (function pointers) ---- */
void dispatch_far(CPU *cpu, uint16_t seg, uint16_t off);
void dispatch_near(CPU *cpu, uint16_t seg, uint16_t off);
void recomp_dispatch(CPU *cpu, uint16_t seg, uint16_t off);

/* ---- Software interrupts (rare in Win16 code; stubbed) ---- */
void int_handler(CPU *cpu, int int_num);
void dos_int21(CPU *cpu);

/* ---- Win16 import shims (21 total) ---- */
/* KERNEL (15) */
void KERNEL_DOS3CALL(CPU *cpu);  /* @102 DOS3CALL */
void KERNEL_FATALAPPEXIT(CPU *cpu);  /* @137 FATALAPPEXIT */
void KERNEL_FATALEXIT(CPU *cpu);  /* @1 FATALEXIT */
void KERNEL_GETDOSENVIRONMENT(CPU *cpu);  /* @131 GETDOSENVIRONMENT */
void KERNEL_GETVERSION(CPU *cpu);  /* @3 GETVERSION */
void KERNEL_GLOBALALLOC(CPU *cpu);  /* @15 GLOBALALLOC */
void KERNEL_GLOBALFREE(CPU *cpu);  /* @17 GLOBALFREE */
void KERNEL_GLOBALLOCK(CPU *cpu);  /* @18 GLOBALLOCK */
void KERNEL_GLOBALREALLOC(CPU *cpu);  /* @16 GLOBALREALLOC */
void KERNEL_GLOBALSIZE(CPU *cpu);  /* @20 GLOBALSIZE */
void KERNEL_GLOBALUNLOCK(CPU *cpu);  /* @19 GLOBALUNLOCK */
void KERNEL_LOCALINIT(CPU *cpu);  /* @4 LOCALINIT */
void KERNEL_LOCKSEGMENT(CPU *cpu);  /* @23 LOCKSEGMENT */
void KERNEL_LSTRLEN(CPU *cpu);  /* @90 LSTRLEN */
void KERNEL___WINFLAGS(CPU *cpu);  /* @178 __WINFLAGS */

/* MSABC110 (1) */
void MSABC110_B_FPSIGNAL(CPU *cpu);  /* @1 B$FPSIGNAL */

/* USER (5) */
void USER_DEFWINDOWPROC(CPU *cpu);  /* @107 DEFWINDOWPROC */
void USER_DESTROYWINDOW(CPU *cpu);  /* @53 DESTROYWINDOW */
void USER_LSTRCMPI(CPU *cpu);  /* @471 LSTRCMPI */
void USER_MESSAGEBOX(CPU *cpu);  /* @1 MESSAGEBOX */
void USER_SHOWWINDOW(CPU *cpu);  /* @42 SHOWWINDOW */

#endif /* CATZ_RUNTIME_API_H */
