/* win16_stubs.c - Auto-generated by gen_win16_stubs.py. */
/* Stub bodies for every Win16 import + interrupt handler, so the   */
/* lifted engine links. Each logs once (with -DCATZ_TRACE_WIN16) and */
/* returns ax=0. Replace with real behavior hottest-API-first.       */
#include "runtime_api.h"
#include <stdio.h>

#ifdef CATZ_TRACE_WIN16
#define WIN16_LOG(n) do { static int _seen; if (!_seen) { _seen = 1; \
    fprintf(stderr, "[win16] %s (stub)\n", (n)); } } while (0)
#else
#define WIN16_LOG(n) ((void)0)
#endif
/* Loud warning the first time an unknown-purge stub runs: its stack
 * cleanup is a guess and may corrupt. Add it to PURGE in win16.py. */
#define WIN16_UNKNOWN(n) do { static int _w; if (!_w) { _w = 1; \
    fprintf(stderr, "[win16] *** %s: unknown stack purge (guessed 0)\n", (n)); \
    } } while (0)

void int_handler(CPU *cpu, int int_num) {
    (void)cpu; WIN16_LOG("int_handler");
    fprintf(stderr, "[int] unhandled INT 0x%02X\n", int_num);
}

/* ===== KERNEL ===== */
void KERNEL_DOS3CALL(CPU *cpu) { (void)cpu; WIN16_LOG("DOS3CALL"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("DOS3CALL"); }
void KERNEL_FATALAPPEXIT(CPU *cpu) { (void)cpu; WIN16_LOG("FATALAPPEXIT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("FATALAPPEXIT"); }
void KERNEL_FATALEXIT(CPU *cpu) { (void)cpu; WIN16_LOG("FATALEXIT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("FATALEXIT"); }
void KERNEL_GETDOSENVIRONMENT(CPU *cpu) { (void)cpu; WIN16_LOG("GETDOSENVIRONMENT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETDOSENVIRONMENT"); }
void KERNEL_LOCKSEGMENT(CPU *cpu) { (void)cpu; WIN16_LOG("LOCKSEGMENT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("LOCKSEGMENT"); }
void KERNEL_LSTRLEN(CPU *cpu) { (void)cpu; WIN16_LOG("LSTRLEN"); cpu->ax = 0; cpu->sp += 4 + 4; }
void KERNEL___WINFLAGS(CPU *cpu) { (void)cpu; WIN16_LOG("__WINFLAGS"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("__WINFLAGS"); }

/* ===== MSABC110 ===== */
void MSABC110_B_FPSIGNAL(CPU *cpu) { (void)cpu; WIN16_LOG("B$FPSIGNAL"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("B$FPSIGNAL"); }

/* ===== USER ===== */
void USER_DEFWINDOWPROC(CPU *cpu) { (void)cpu; WIN16_LOG("DEFWINDOWPROC"); cpu->ax = 0; cpu->sp += 4 + 10; }
void USER_DESTROYWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("DESTROYWINDOW"); cpu->ax = 0; cpu->sp += 4 + 2; }
void USER_LSTRCMPI(CPU *cpu) { (void)cpu; WIN16_LOG("LSTRCMPI"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("LSTRCMPI"); }

