"""
gen_segments_h.py - Regenerate runtime/segments.h from lifted sources.

Scans src/seg*.c for `void segNNN_XXXX(CPU *cpu)` definitions and emits matching
prototypes, plus the protected-mode selector placeholders (SEG_n). Generating
prototypes directly from definitions guarantees they always match, so every
cross-segment call resolves at link time.
"""
import os
import re
import glob

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'runtime', 'segments.h')

DEF_RE = re.compile(r'^void (seg\d+_[0-9A-Fa-f]+)\(CPU \*cpu\)', re.M)


def main():
    # Map each function name to the segment number it belongs to (segNNN_XXXX),
    # scanning every .c (incl. generated stubs) so prototypes cover all defs.
    funcs_by_seg = {}
    seen = set()
    for path in sorted(glob.glob(os.path.join(SRC, '*.c'))):
        text = open(path, encoding='utf-8', errors='replace').read()
        for name in DEF_RE.findall(text):
            if name in seen:
                continue
            seen.add(name)
            seg = 'seg' + str(int(name[3:name.index('_')]))
            funcs_by_seg.setdefault(seg, []).append(name)

    lines = []
    lines.append('/* segments.h - Forward declarations for all lifted functions */')
    lines.append('/* Auto-generated by gen_segments_h.py - do not edit manually */')
    lines.append('')
    lines.append('#ifndef CATZ_SEGMENTS_H')
    lines.append('#define CATZ_SEGMENTS_H')
    lines.append('')
    lines.append('#include "cpu.h"')
    lines.append('#include "runtime_api.h"')
    # JET_SETJMP is a macro because the anchor has to live in the frame that
    # calls setjmp; the lifter wraps each Jet setjmp call site in it.
    lines.append('#include "jet_setjmp.h"')
    lines.append('')
    lines.append('/* ---- SEGMENT SELECTOR PLACEHOLDERS ----')
    lines.append(' * Protected-mode NE selectors map to flat-memory bases at runtime.')
    lines.append(' * Placeholder: selector == NE segment index. Replace with a real')
    lines.append(' * selector->base table when the protected-mode memory model lands. */')
    # Cover every global segment present in the lift -- not just those with
    # lifted functions, but also data segments whose selector is pushed in code
    # (e.g. MSAJT110's DGROUP @146). Take the max of function-segs and any
    # SEG_<n> referenced anywhere in src, plus headroom.
    import re as _re
    seg_ref = 0
    for path in glob.glob(os.path.join(SRC, '*.c')):
        for m in _re.findall(r'\bSEG_(\d+)\b', open(path, encoding='utf-8', errors='replace').read()):
            seg_ref = max(seg_ref, int(m))
    max_seg = max([int(k[3:]) for k in funcs_by_seg] + [seg_ref, 66])
    for n in range(1, max_seg + 2):
        lines.append(f'#define SEG_{n} ((uint16_t){n})')
    lines.append('')

    total = 0
    for seg in sorted(funcs_by_seg, key=lambda s: int(s[3:])):
        names = funcs_by_seg[seg]
        lines.append(f'/* {seg} ({len(names)} functions) */')
        for name in names:
            lines.append(f'void {name}(CPU *cpu);')
            total += 1
        lines.append('')

    lines.append('#endif /* CATZ_SEGMENTS_H */')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'Wrote {OUT}: {total} prototypes across {len(funcs_by_seg)} segments')


if __name__ == '__main__':
    main()
