"""
gen_stubs.py - Emit stub definitions for unresolved cross-segment call targets.

The linear-sweep disassembler desyncs on data embedded in code, so some near/far
call targets land mid-instruction and never get a real lifted function. Other
code still calls `segNNN_XXXX(cpu)`, leaving the symbol undefined at link time.

This writes empty stub definitions for every called-but-undefined seg target so
the program links. Each stub is a NO-OP and is reported as a coverage gap; the
real fix is a recursive-traversal disassembler that aligns these targets.
"""
import os
import re
import glob

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(SRC, '_unresolved_stubs.c')

DEF_RE = re.compile(r'^void (seg\d+_[0-9A-Fa-f]+)\(CPU \*cpu\)', re.M)
CALL_RE = re.compile(r'\b(seg\d+_[0-9A-Fa-f]+)\(cpu\)')


def main():
    defined = set()
    called = set()
    # The runtime hand-writes a few segNNN_XXXX bodies for guest functions the
    # lifted model cannot express (Jet's longjmp). Those are definitions too;
    # stubbing them as well is a duplicate symbol.
    for path in (glob.glob(os.path.join(SRC, '*.c'))
                 + glob.glob(os.path.join(ROOT, 'runtime', '*.c'))
                 + glob.glob(os.path.join(ROOT, 'runtime', 'win16', '*.c'))):
        if os.path.basename(path) == os.path.basename(OUT):
            continue
        text = open(path, encoding='utf-8', errors='replace').read()
        defined.update(DEF_RE.findall(text))
        called.update(CALL_RE.findall(text))

    undefined = sorted(called - defined)

    lines = [
        '/* _unresolved_stubs.c - Auto-generated by gen_stubs.py */',
        '/* Stubs for call targets the disassembler could not align to an */',
        '/* instruction boundary (data-in-code desync). Coverage gap, not final. */',
        '/* CRITICAL: each stub performs a proper FAR RETURN (pops the cs:ip that */',
        '/* dispatch_far pushed). A do-nothing stub leaves the 4-byte return addr */',
        '/* on the guest stack -> the caller\'s pop ds/si/etc read the 0xFFFF */',
        '/* sentinel or a neighbouring value, corrupting segment regs (this caused */',
        '/* the Jet-context DS=230 / host DS=FFFF hangs). Returning keeps the stack */',
        '/* balanced for a retf-0 callee; promote to a real fn via FORCE_PROMOTE */',
        '/* (lift_combined.py) when the function must actually do work. */',
        '',
        '#include "segments.h"',
        '#include <stdio.h>',
        '',
        '#ifdef CATZ_LOG_UNRESOLVED',
        '#define UNRES_LOG(n) fprintf(stderr, "[UNRESOLVED] %s called (far-return)\\n", n)',
        '#else',
        '#define UNRES_LOG(n) ((void)0)',
        '#endif',
        '',
    ]
    for name in undefined:
        lines.append(
            f'void {name}(CPU *cpu) {{ UNRES_LOG("{name}"); '
            f'uint16_t _ip=pop16(cpu); uint16_t _cs=pop16(cpu); '
            f'recomp_dispatch(cpu,_cs,_ip); }} /* UNRESOLVED target -> far return */')
    lines.append('')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))

    print(f'Wrote {OUT}: {len(undefined)} unresolved stubs '
          f'({len(defined)} real functions, {len(called)} distinct call targets)')


if __name__ == '__main__':
    main()
